"""create tables

Revision ID: c83329710135
Revises:
Create Date: 2025-08-21 20:43:22.775507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c83329710135"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("login", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admins")),
        sa.UniqueConstraint(
            "hashed_password", name=op.f("uq_admins_hashed_password")
        ),
        sa.UniqueConstraint("login", name=op.f("uq_admins_login")),
    )
    op.create_table(
        "appointments",
        sa.Column(
            "first_name",
            sa.String(length=100),
            nullable=False,
            comment="Имя пациента",
        ),
        sa.Column(
            "last_name",
            sa.String(length=100),
            nullable=False,
            comment="Фамилия пациента",
        ),
        sa.Column(
            "phone_number",
            sa.String(length=20),
            nullable=False,
            comment="Номер телефона пациента",
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=True,
            comment="Email пациента",
        ),
        sa.Column(
            "age",
            sa.String(length=20),
            nullable=False,
            comment="Возрастная группа",
        ),
        sa.Column(
            "preferred_time",
            sa.String(length=50),
            nullable=True,
            comment="Предпочтительное время",
        ),
        sa.Column(
            "message",
            sa.Text(),
            nullable=True,
            comment="Дополнительное сообщение",
        ),
        sa.Column(
            "privacy_consent",
            sa.Boolean(),
            nullable=False,
            comment="Согласие на обработку",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("appointments")
    op.drop_table("admins")
    # ### end Alembic commands ###
