"""create admin model

Revision ID: 4864ae78f549
Revises: 576be8db6863
Create Date: 2025-07-25 17:18:23.860435

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4864ae78f549"
down_revision: Union[str, Sequence[str], None] = "576be8db6863"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("login", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admins")),
        sa.UniqueConstraint(
            "hashed_password", name=op.f("uq_admins_hashed_password")
        ),
        sa.UniqueConstraint("login", name=op.f("uq_admins_login")),
    )
    op.alter_column(
        "appointments",
        "status",
        existing_type=postgresql.ENUM(
            "new", "confirmed", "canceled", name="appointment_status"
        ),
        comment=None,
        existing_comment="Статус записи",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "appointments",
        "status",
        existing_type=postgresql.ENUM(
            "new", "confirmed", "canceled", name="appointment_status"
        ),
        comment="Статус записи",
        existing_nullable=False,
    )
    op.drop_table("admins")
    # ### end Alembic commands ###
